import React from 'react'

const AboutSection = () => {
  return (
    <div className='flex w-screen items-center justify-center my-8 lg:my-16'>
      <div className='flex flex-col items-start justify-start w-[87.79%] md:w-[91.4%] lg:w-[76.8%] text-start gap-[10px] lg:gap-[20px]'>
        <h3 className='text-[28px] md:text-[32px] lg:text-[36px] font-marcellus font-semibold mb-[30px]'>İnternet Sitesi Hakkında</h3>
        <h4 className='text-[24px] lg:text-[30px] font-jost font-medium mb-[15px]'>I - İnternet sitesi</h4>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>Gümrük ve Ticaret Bakanlığı bağımsız denetime tabi şirketlere yönelik internet sitesi açma zorunluluğunu, “Sermaye Şirketlerinin Açacakları İnternet Sitelerine Dair Yönetmelik” ile belirlemiş olup, yayınlamış olan bu yönetmelik bağımsız denetime tabi olan şirketleri kapsamaktadır.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>Yönetmeliğin 5. Maddesinin 2. Bendinde; “Bu yönetmeliğin yürürlüğe girdiği tarihten sonra kapsama dahil olan sermaye şirketlerinin, kapsama girdikleri tarihten itibaren üç ay içinde internet sitesi açmaları ve bu sitenin belirli bir bölümünü şirketçe kanunen yapılması gereken ilanların yayımlanması için özgülemeleri gerekir.” hükmü yer almaktadır.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>Buna göre bağımsız denetime tabi olan şirketlerin bağımsız denetime tabi oldukları tarihten itibaren 3 ay içinde internet sitesi kurmak veya var olan internet sitesini bu yönetmelikte belirlenen hususlara uygun hale getirmeleri gerekmektedir.</p>

        <span className='text-[12px] lg:text-[14px] leading-normal font-jost font-bold'>İnternet sitesi kurmayla ilgili TTk maddeleri aşağıda gösterilmiştir:</span>
        <h5  className='text-[16px] lg:text-[20px] font-jost font-bold'>TTK. MADDE 1524- (Değişik: 26/6/2012-6335/34 md.)</h5>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(1) 397 nci maddenin dördüncü fıkrası uyarınca denetime tabi olan sermaye şirketleri, kuruluşlarının ticaret siciline tescili tarihinden itibaren üç ay içinde bir internet sitesi açmak ve bu sitenin belirli bir bölümünü şirketçe kanunen yapılması gereken ilanların yayımlanmasına özgülemek zorundadır. İnternet sitesinde yayımlanacak içerikler, bu Kanunda belli bir süre belirtilmiş ise bu süre içinde, belirtilmemiş ise içeriğin dayandığı işlemin veya olgunun gerçekleştiği tarihten, tescil veya ilana bağlandığı durumlarda ise tescil veya ilanın yapıldığı tarihten itibaren en geç beş gün içinde, şirketin kuruluşundan internet sitesi açılıncaya kadar geçen sürede yayımlanması gereken içerikler de bu sitenin açıldığı tarihte siteye konulur.        </p>
        <p className='text-[14px] lg:text-[16px] leading-normal font-jost'>(5) Bu Kanun ve ilgili diğer kanunlarda veya idari düzenlemelerde daha uzun bir süre öngörülmedikçe, şirketin internet sitesine konulan bir içerik, üzerinde bulunan tarihten itibaren en az altı ay süreyle internet sitesinde kalır, aksi hâlde konulmamış sayılır.</p>

        <span className='text-[12px] lg:text-[14px] leading-normal font-jost font-bold'>Suçlar ve cezalar</span>
        <h5  className='text-[16px] lg:text-[20px] font-jost font-bold'>MADDE 562- (Değişik: 26/6/2012-6335/30 md.)         </h5>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(12) 1524 üncü maddede öngörülen internet sitesini oluşturmayan şirketlerin yönetim organı üyeleri, yüz günden üçyüz güne kadar adli para cezasıyla ve aynı madde uyarınca internet sitesine konulması gereken içeriği usulüne uygun bir şekilde koymayan bu fıkrada sayılan failler yüz güne kadar adli para cezasıyla cezalandırılır.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(13) Bu Kanun kapsamındaki idari para cezaları, aksine hüküm bulunmayan hâllerde, mahallin en büyük mülki amiri tarafından verilir.        </p>
        <h5  className='text-[16px] lg:text-[20px] font-jost font-bold'>GEÇİCİ MADDE 8- (Ek: 26/6/2012-6335/38 md.)         </h5>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(1) 1524 üncü maddenin yürürlüğe girdiği tarihten önce kurulan denetime tabi sermaye şirketlerinden internet sitesine sahip olanlar söz konusu maddenin yürürlüğünden itibaren üç ay içinde internet sitelerinin belli bir bölümünü 1524 üncü maddedeki içeriklerin yayımlanmasına özgülemek, internet sitesi olmayanlar ise aynı süre içinde internet sitesi açmak ve bu sitenin belli bir bölümünü anılan maddedeki içeriklerin yayımlanmasına özgülemek zorundadır.</p>
        <span className='text-[12px] lg:text-[14px] leading-normal font-jost font-bold'>İnternet sitesinde yayımlanan içerik        </span>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>  <span className='font-bold'>MADDE 6 –</span> (1) İnternet sitesinin açılması ile birlikte aşağıdaki içerikler internet sitesinde sürekli olarak yayımlanır.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>a) Şirketin MERSİS numarası, ticaret unvanı, merkezi, taahhüt edilen ve ödenen sermaye miktarı ile anonim şirketlerde yönetim kurulu başkan ve üyelerinin, limited şirketlerde müdürlerin, sermayesi paylara bölünmüş komandit şirketlerde yöneticilerin ad ve soyadları. <span className='text-red-600 font-semibold'>(Bkz. TTK Md.39/1)</span> </p> 
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>) Bir tüzel kişinin; anonim şirketlerde yönetim kuruluna üye olarak limited şirketlerde müdür olarak seçilmesi durumunda; tüzel kişiyle birlikte, tüzel kişi adına tüzel kişi tarafından  belirlenen gerçek  kişinin de tescil ve ilan olunduğuna ilişkin açıklama, seçilen tüzel kişinin MERSİS numarası, ticaret unvanı, merkezi ve tüzel kişi ile birlikte tescil edilen gerçek kişinin adı ve soyadı. <span className='text-red-600 font-semibold'> (Bkz. TTK Md.39/1 VE TTK 359/1)</span>       </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>c) Seçilen denetçinin adı ve soyadı/unvanı, yerleşim yeri/merkezi, varsa tescil edilmiş şubesi.  <span className='text-red-600 font-semibold'>(TTK 399/1)</span> </p> 
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>Birinci fıkra uyarınca yayımlanan içeriklerde değişiklik olması halinde bu içeriklerin yeni hali, değişikliğin meydana geldiği tarihte internet sitesinde yayımlanır.</p>(2)
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(3) Şirketçe internet sitesinde en az altı aylık süre için yayımlanması gereken hususlar aşağıda belirtilmiştir.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>a) Kanunun 149 uncu maddesinin birinci fıkrasına göre, birleşme sözleşmesi, birleşme raporu, son üç yılın finansal tabloları ile yıllık faaliyet raporları, gereğinde ara bilançoları ortakların incelemesine sunulmak üzere genel kurul kararından önceki otuz gün içinde internet sitesine konur. <span className='text-red-600 font-semibold'> (TTK 149/1)</span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>b) Bu fıkranın (a) bendinde sayılan belgelerde inceleme yapma hakkının belirtildiği, bu belgelerin nereye tevdi edildiklerine ve nerelerde incelemeye hazır tutulduklarına ilişkin ilan, belgelerin tevdi tarihinden itibaren en az üç iş günü öncesinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>c) Birleşmeye katılan şirketlerin, alacaklılarına, alacaklarının teminat altına alınması için talepte bulunabileceklerine dair sicil gazetesinde yedişer gün arayla üç defa yapılan ilan,  birinci ilanın sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.<span className='text-red-600 font-semibold'> (TTK 157/2)</span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>ç) Bölünmeye katılan şirketlerden her biri tarafından, Kanunun 171 inci maddesi uyarınca bölünme sözleşmesi veya planı, bölünme raporu, son üç yılın finansal tabloları ile yıllık faaliyet raporları ve varsa ara bilançoları üzerinde inceleme yapma hakkına işaret eden ve bu belgelerin nereye tevdi edildiklerine ve nerelerde incelemeye hazır tutulduklarına dair ilan, bölünme kararının alındığı tarihten iki ay önce internet sitesine konur. <span className='text-red-600 font-semibold'> (TTK 171/4)</span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>d) Bölünmeye katılan şirketler tarafından alacaklıların alacaklarını bildirmeye ve teminat verilmesi için talepte bulunmaya çağrılmasına ilişkin sicil gazetesinde yedişer gün arayla üç defa yapılan ilan, birinci ilanın sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur. <span className='text-red-600 font-semibold'> (TTK 174/1) </span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>e) Şirkete fesih davası açılmış ise davanın açıldığı hususu, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur. <span className='text-red-600 font-semibold'> (TTK 353/5)</span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>f) Şirkete açılan fesih davasına ilişkin kesinleşmiş olan mahkeme kararı, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> g) Genel kurulun toplantıya çağrılmasına ilişkin ilan en geç sicil gazetesinde yayımlandığı tarihte internet sitesine konur. <span className='text-red-600 font-semibold'>(TTK 414/1)</span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>ğ) Anonim şirket genel kurulunda, finansal tabloların ve buna bağlı konuların müzakeresinin bir ay sonraya ertelenmesi halinde, bu duruma ilişkin pay sahiplerine yapılan ilan, erteleme kararı tarihinden itibaren en geç beş gün içinde internet sitesine konur. <span className='text-red-600 font-semibold'>(TTK 420/1) </span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> h) Şirketin genel kurul toplantı tutanağı ile imtiyazlı pay sahipleri özel kurulunun toplantı tutanağı genel kurul tarihinden itibaren en geç beş gün içinde internet sitesine konur.<span className='text-red-600 font-semibold'> (TTK 422/2)</span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> ı) Kanunun 428 inci maddesi uyarınca organın temsilcisi, bağımsız temsilcisi ve kurumsal temsilciliğe ilişkin ilanlar, ilanın yayımlandığı gün internet sitesine konur. <span className='text-red-600 font-semibold'>(TTK 428/1-2)</span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> i) Genel kurul kararına karşı iptal veya butlan davasının açıldığı hususu ve duruşma günü, şirket sözleşmesine uygun olarak yapılan ilan tarihinden itibaren en geç beş gün içinde internet sitesine konur. <span className='text-red-600 font-semibold'>(TTK 448/1)</span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> j) Genel kurul kararının iptaline veya butlanına ilişkin kesinleşmiş mahkeme kararı, tescil tarihinden itibaren en geç beş gün içinde internet sitesine konur. <span className='text-red-600 font-semibold'>(TTK 450/1)</span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>k) Şirket sözleşmesinin değiştirilmesine ilişkin genel kurul kararı, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.  <span className='text-red-600 font-semibold'>(TTK 455/1)</span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>l) Kayıtlı sermaye sisteminde yönetim kurulunun sermayenin artırılmasına ilişkin kararı, çıkarılmış sermayeyi gösteren esas sözleşme maddesinin yeni şekli, yeni payların itibarî değerleri, cinsleri, sayıları, imtiyazlı olup olmadıkları, imtiyazlı paylara ve rüçhan haklarına ilişkin sınırlamalar ve kullanılma şartları ile bunların süresi, prime dair kayıtlar ve bunun uygulanması hakkındaki kurallar şirket sözleşmesine uygun olarak yapılan ilan tarihinden itibaren en geç beş gün içinde internet sitesine konur.       <span className='text-red-600 font-semibold'>(TTK 460/2)</span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>m) Yeni pay alma hakkının kullanılabilmesinin esaslarının belirlenmesine ilişkin yönetim kurulunun kararı, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur. <span className='text-red-600 font-semibold'>(TTK 461/3) </span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>n) Esas sermayenin azaltılması durumunda, sermaye azaltılmasına gidilmesinin sebepleri ile azaltmanın amacı ve azaltmanın ne şekilde yapılacağına ilişkin ayrıntılı açıklamalar, bu açıklamaların da yer aldığı genel kurul toplantısına ilişkin çağrı ilanının sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>o) Genel kurulun esas sermayenin azaltılmasına ilişkin kararı üzerine alacaklılara sicil gazetesinde yedişer gün arayla üç defa yapılan ilan, birinci ilanın yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.  <span className='text-red-600 font-semibold'>(TTK 473/1)</span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> ö) Mütemerrit pay sahibine temerrüde konu olan pay tutarını bir ay içinde ödemesi, aksi halde, ilgili paylara ilişkin haklarından yoksun bırakılacağı ve sözleşme cezasının isteneceğine ilişkin yapılan davet ve ihtar mesajı, bu davet ve ihtarın sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur. Nama yazılı pay senedi sahiplerine, davet ve ihtarın ilan yerine iadeli taahhütlü mektupla yapılması halinde, bu davet ve ihtar iadeli taahhütlü mektubun gönderildiği tarihten itibaren en geç beş gün içinde internet sitesine konur. <span className='text-red-600 font-semibold'>(TTK 483/1,  483/2)</span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>p) Yönetim kurulunun hamiline yazılı pay senetlerinin bastırılmasına ilişkin kararı, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.  <span className='text-red-600 font-semibold'>(TTK 486/2)</span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>r) Alacaklı oldukları, şirket defterlerinden veya diğer belgelerden anlaşılamayan ya da yerleşim yerleri bilinmeyen diğer alacaklılara yönelik şirketin sona ermiş bulunduğu konusunda bilgilendirilmelerine ve alacaklarını tasfiye memurlarına bildirmeye çağrılmalarına ilişkin sicil gazetesinde birer hafta arayla üç defa yapılan ilan, birinci ilanın yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur. <span className='text-red-600 font-semibold'>(TTK 541/1) </span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>s) Şirketler topluluğuna dahil bir teşebbüs tarafından payların, Kanunun 198 inci maddesinde belirtilen oranlarda kazanılması veya elden çıkarılmasına ilişkin açıklama, gerçekleşme tarihinden itibaren en geç beş gün içinde internet sitesine konur. </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>ş) Kanunun 966 ncı maddesinin birinci fıkrası uyarınca malik ve diğer hak sahiplerinin kimler olduğunun veya yerleşim yerlerinin belli olmadığı hallerde, geminin gemi sicilinden silinmesine ve belirlenen süreye ilişkin olarak sicil gazetesinde yapılan ilan, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesinde de ilan edilir.  <span className='text-red-600 font-semibold'>(TTK Md 966/1)</span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>t) Şirketler topluluğuna dahil olan teşebbüsün ve sermaye şirketinin yönetim kurulu üyeleriyle yöneticilerinin, kendileri, eşleri, velayetleri altındaki çocukları ve bunların, sermayelerinin en az yüzde yirmisine sahip bulundukları ticaret şirketlerinin o sermaye şirketindeki payları ile ilgili olarak yapacakları açıklama, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>u) Şirketler arasında yapılan hakimiyet sözleşmesi sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur. </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>ü) Şirketteki pay sahibi/ortak sayısının bire düşmesi ya da şirketin tek pay sahipli/ortaklı olarak kurulması halinde, şirketin tek pay sahipli/ortaklı olduğu hususu ve tek pay sahibi/ortağın adı, soyadı, yerleşim yeri ve vatandaşlığına dair bilgiler sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur. </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>v) Şirket sözleşmesi ve değişiklikler kuruluşun ya da değişikliğin sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur. </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> y) Şirketin tescilinden itibaren iki yıl içinde bir işletme veya aynın, sermayenin onda birini aşan bir bedel karşılığında devralınmasına veya kiralanmasına ilişkin sözleşme sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>z) Yönetim kurulunun veya müdürler kurulunun temsile yetkili kişileri ve bunların temsil şekillerini gösterir kararı, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur. </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>aa) Anonim şirketlerde genel kurulun çalışma usul ve esaslarını içeren iç yönerge ilan tarihini izleyen beş gün içinde internet sitesine konur. </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>bb) Yönetim kurulunun rüçhan hakkının sınırlandırılmasının veya kaldırılmasının gerekçelerini, yeni payların primli ve primsiz çıkarılmasının sebeplerini, primin nasıl hesaplandığını gösteren raporu sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur. </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>cc) Sermayenin azaltılmasının sebepleri ile azaltmanın amacı ve azaltmanın ne şekilde yapılacağını gösterir yönetim/müdürler kurulunca hazırlanmış ve genel kurul tarafından onaylanmış sermayenin azaltılmasına ilişkin rapor, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur. (TTK 474/1) <span className='text-red-600 font-semibold'>(TTK 474/1)</span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>çç) Yönetim/müdürler kurulunun pay bedellerinin ödenmesine ilişkin çağrı ilanı yapıldığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>dd) Yönetim kurulunun mütemerrit pay sahibinin senedini iptal etmesine ilişkin kararı sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>ee) Yönetim kurulu veya müdürler kurulu ile genel kurul toplantılarının elektronik ortamda yapılması veya bu toplantılara elektronik ortamda katılım sağlanması hallerinde, elektronik ortam araçlarının etkin katılmaya elverişliliğinin ispatlandığı teknik rapor, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.    <span className='text-red-600 font-semibold'>(TTK 1527/3,6)</span></p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> (4) İnternet sitesinin bilgi toplumu hizmetlerine özgülenmiş kısmında yayımlanan içeriğin başına tarih ve parantez içinde “yönlendirilmiş mesaj” ibaresi konulur. Yönlendirilmiş mesaj zaman damgası ile oluşturulur ve aynı yöntemle değiştirilir.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(5) Kanun ve diğer kanunlar uyarınca yapılması gereken ilanlar, ilgili mevzuatta öngörüldüğü şekilde internet sitesinde yayımlanır. </p>
        <span className='text-[14px] lg:text-[16px] leading-normal font-jost font-semibold text-red-600 uppercase'>TTK DA YER ALAN İLAVE HÜKÜMLER </span>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-bold'>TTK- MADDE 198- (1) </span> Bir teşebbüs, bir sermaye şirketinin sermayesinin, doğrudan veya dolaylı olarak, yüzde beşini, onunu, yirmisini, yirmibeşini, otuzüçünü, ellisini, altmışyedisini veya yüzde yüzünü temsil eden miktarda paylarına sahip olduğu veya payları bu yüzdelerin altına düştüğü takdirde; teşebbüs, durumu söz konusu işlemlerin tamamlanmasını izleyen on gün içinde, sermaye şirketine ve bu Kanun ile diğer kanunlarda gösterilen yetkili makamlara bildirir. Payların yukarıda belirtilen oranlarda kazanılması veya elden çıkarılması, yıllık faaliyet ve denetleme raporlarında ayrı  bir  başlık altında açıklanır ve sermaye şirketinin internet sitesinde ilan edilir.  </p>
        <h5  className='text-[16px] lg:text-[20px] font-jost font-bold'>GEÇİCİ MADDE 7- (Ek: 26/6/2012-6335/38 md.)         </h5>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(1) Bu Kanunun yürürlüğe girdiği tarihten itibaren iki yıl içinde aşağıdaki hâlleri tespit edilen ya da bildirilen anonim ve limited şirketler ile kooperatiflerin tasfiyeleri ve ticaret sicilinden kayıtlarının silinmesi, ilgili kanunlardaki tasfiye usulüne uyulmaksızın bu madde uyarınca yapılır. </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> 4) Ticaret sicili müdürlüklerince;</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> a) Kapsam dâhilindeki şirket ve kooperatiflerin ticaret sicilindeki kayıtlı son adreslerine ve sicil kayıtlarına göre şirket veya kooperatifi temsil ve ilzama yetkilendirilmiş kişilere bir ihtar yollanır. Yapılacak ihtar, ilan edilmek üzere Türkiye Ticaret Sicili Gazetesi Müdürlüğüne aynı gün gönderilir. İlan, ihtarın ulaşmadığı durumlarda, ilan tarihinden itibaren otuzuncu günün akşamı itibarıyla, 11/2/1959 tarihli ve 7201 sayılı Tebligat Kanunu hükümlerine göre yapılmış tebligat yerine geçer. Ayrıca anılan ilan, bildirici niteliği haiz olarak ilgili ticaret ve sanayi odası veya ticaret, sanayi ya da deniz ticaret odasının internet sitesinde aynen yayımlanır.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>  (5) b) Dördüncü fıkra uyarınca yapılan ihtar ve ilan üzerine süresi içinde tasfiye memurlarını bildiren şirket ve kooperatiflerin, tasfiye memurları ve tasfiye adresi, ilgili ticaret sicili müdürlüğü tarafından tescil ve Türkiye Ticaret Sicili Gazetesinde ve ilgili odanın internet sitesinde ilan edilir.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> (11) Dördüncü fıkra uyarınca yapılan ihtar ve ilana rağmen, süresi içinde cevap vermeyen veya tasfiye memurunu bildirmeyen yahut durumunu kanuna uygun hâle getirmeyen veya faaliyette bulunduğunu adres ve kanıtlarıyla birlikte bildirmeyen şirket ve kooperatiflerin unvanı ticaret sicilinden resen silinir. Resen unvanı silinen şirket ve kooperatifler, Türkiye Ticaret Sicili Gazetesi ile ilgili odanın internet sitesinde ilan edilir. </p>
      </div>
    </div>
  )
}

export default AboutSection
