import React from 'react'

const WebRuleSection = () => {
  return (
    <div className='flex w-screen items-center justify-center my-8 lg:my-16'>
      <div className='flex flex-col items-start justify-start w-[87.79%] md:w-[91.4%] lg:w-[76.8%] text-start gap-[10px] lg:gap-[20px] font-jost'>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>31 Mayıs 2013 Tarihli Resmi Gazete</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>Sayı: 28663</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>Gümrük ve Ticaret Bakanlığından: </p>
        <h3 className='text-[28px] md:text-[32px] lg:text-[32px] font-marcellus font-bold mb-[30px]'>SERMAYE ŞİRKETLERİNİN AÇACAKLARI İNTERNET SİTELERİNE DAİR YÖNETMELİK</h3>
        <h4 className='text-[20px] lg:text-[24px] font-jost font-medium mb-[15px]'>BİRİNCİ BÖLÜM</h4>
        <h5 className='text-[14px] lg:text-[16px] font-semibold'>Amaç, Kapsam, Dayanak ve Tanımlar </h5>
        <p className='text-[12px] lg:text-[14px] font-semibold'>Amaç</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>Gümrük ve Ticaret Bakanlığı bağımsız denetime tabi şirketlere yönelik internet sitesi açma zorunluluğunu, “Sermaye Şirketlerinin Açacakları İnternet Sitelerine Dair Yönetmelik” ile belirlemiş olup, yayınlamış olan bu yönetmelik bağımsız denetime tabi olan şirketleri kapsamaktadır.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>MADDE 1 –</span> (1) Bu Yönetmeliğin amacı, 13/1/2011 tarihli ve 6102 sayılı Türk Ticaret Kanununun 1524 üncü maddesinin birinci fıkrası uyarınca internet sitesi açılmasına ve bu sitenin belirli bir bölümünün şirketçe kanunen yapılması gereken ilanların yayımlanması için özgülenmesine ve bilgi toplumu hizmetlerine ayrılmasına ilişkin usul ve esasları düzenlemektir.</p>
        <p className='text-[12px] lg:text-[14px] font-semibold'>Kapsam</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>MADDE 2 –</span>(1) Bu Yönetmelik, 6102 sayılı Kanunun 397 nci maddesi uyarınca Bakanlar Kurulu tarafından belirlenen denetime tabi sermaye şirketleri tarafından açılacak internet sitelerinde ilan edilecek ve erişime açık tutulacak asgari içeriğe, denetime tabi sermaye şirketleri ile Merkezi Veri Tabanı Hizmet Sağlayıcıların yapacakları işlemlere ve bu işlemlerden kaynaklanan yükümlülüklere ilişkin usul ve esasları kapsamaktadır.</p>
        <p className='text-[12px] lg:text-[14px] font-semibold'>Dayanak</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>MADDE 3 –</span>(1) Bu Yönetmelik, 6102 sayılı Kanunun 397 nci maddesi uyarınca Bakanlar Kurulu tarafından belirlenen denetime tabi sermaye şirketleri tarafından açılacak internet sitelerinde ilan edilecek ve erişime açık tutulacak asgari içeriğe, denetime tabi sermaye şirketleri ile Merkezi Veri Tabanı Hizmet Sağlayıcıların yapacakları işlemlere ve bu işlemlerden kaynaklanan yükümlülüklere ilişkin usul ve esasları kapsamaktadır.</p>
        <p className='text-[12px] lg:text-[14px] font-semibold'>Tanımlar ve kısaltmalar</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>MADDE 4 –</span>(1) Bu Yönetmelikte geçen;</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> a) Bakanlık: Gümrük ve Ticaret Bakanlığını,</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>b) Bilgi toplumu hizmeti: Fiziki olarak karşı karşıya gelmeksizin, bedelli veya bedelsiz olarak elektronik ortamda yerine getirilen çevrim içi hizmetleri, </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> c) ÇİSDuP (Online Certificate Status Protocol-OCSP) : Çevrimiçi Sertifika Durum Protokolü Sunucusunu,</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> ç) Güvenli elektronik imza: 15/1/2004 tarihli ve 5070 sayılı Elektronik İmza Kanununun 4 üncü maddesinde tanımlanan elektronik imzayı,</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> d) ISO/IEC (International Organisation for Standardisation/International Electrotechnical Commitee): Uluslararası Standardizasyon Teşkilatı/Uluslararası Elektroteknik Komitesini</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> e) İnternet sitesi: Kanunun 1524 üncü maddesinde belirtilen asgari içeriğe sahip elektronik platformu,</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> f) Kanun: 13/1/2011 tarihli ve 6102 sayılı Türk Ticaret Kanununu,</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> g) Merkezi Kayıt Kuruluşu (MKK): 6/12/2012 tarihli ve 6362 sayılı Sermaye Piyasası Kanununun 81 inci maddesi uyarınca kurulmuş olan Merkezi Kayıt Kuruluşunu,</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> ğ) Merkezi Sicil Kayıt Sistemi (MERSİS): Ticaret sicili işlemlerinin elektronik ortamda yürütüldüğü, ticaret sicili kayıtları ile tescil ve ilan edilmesi gereken içeriklerin düzenli olarak depolandığı ve elektronik ortamda sunulduğu Gümrük ve Ticaret Bakanlığı ile Türkiye Odalar ve Borsalar Birliği nezdinde oluşturulan ve işletilen merkezi ortak veri tabanını da içeren bilgi sistemini,</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> h) Merkezi Veri Tabanı Hizmet Sağlayıcı (MTHS): Kanunun 1524 üncü maddesi ve bu Yönetmelik uyarınca şirketlerin kendi internet sitelerinin özgülenmiş kısmında erişime açılması gereken içeriği güvenli ortamda tutma, şirketin erişimine hazır bulundurma ve arşivleme dahil olmak üzere Bakanlıkça belirlenmiş diğer faaliyetleri yürüten özel hukuk tüzel kişisini,</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> ı) MERSİS numarası: MERSİS tarafından verilen ve özel algoritma ile üretilmiş tekil numarayı,</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> i) Sicil gazetesi: Türkiye Ticaret Sicili Gazetesini,</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>j) SİL: Sertifika İptal Listesini, </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> k) Şirket: Kanunun 397 nci maddesi uyarınca Bakanlar Kurulunca belirlenen denetime tabi sermaye şirketlerini,        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>l) Şirket sözleşmesi: Anonim ve sermayesi paylara bölünmüş komandit şirketlerde esas sözleşmeyi, limited şirketlerde ise şirket sözleşmesini, </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> m) Yönlendirilmiş mesaj: İnternet sitesinin Kanunun 1524 üncü maddesinin amaçlarına özgülenmiş kısmında yayımlanan ve ilgili tüm taraflara yönlendirildiği karine olarak kabul edilen her türlü içeriği,</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> n) Zaman damgası: 5070 sayılı Elektronik İmza Kanununun 3 üncü maddesinin birinci fıkrasının (h) bendinde tanımlanan kaydı, <br/> ifade eder.</p>
        <h4 className='text-[20px] lg:text-[24px] font-jost font-medium mb-[15px]'>İKİNCİ BÖLÜM</h4>
        <h5 className='text-[14px] lg:text-[16px] font-semibold'>İnternet Sitesi Açma ve Destek Hizmeti Alma</h5>
        <p className='text-[12px] lg:text-[14px] font-semibold'>İnternet sitesi açma ve tescil zorunluluğu ile destek hizmeti temini        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>MADDE 5 – </span>(1) Bu Yönetmeliğin yürürlüğe girdiği tarihten itibaren kurulan şirketlerin kuruluşlarının ticaret siciline tescil edildiği tarihten itibaren üç ay içinde internet sitesi açmaları ve bu sitenin belirli bir bölümünü şirketçe kanunen yapılması gereken ilanların yayımlanması için özgülemeleri gerekir.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>2) Bu Yönetmeliğin yürürlüğe girdiği tarihten sonra kapsama dahil olan sermaye şirketlerinin, kapsama girdikleri tarihten itibaren üç ay içinde internet sitesi açmaları ve bu sitenin belirli bir bölümünü şirketçe kanunen yapılması gereken ilanların yayımlanması için özgülemeleri gerekir. </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(3) Şirketler, internet sitesine ilişkin yükümlülüklerini doğrudan kendileri yerine getirebilecekleri gibi MTHS’lerden destek hizmeti almak suretiyle de yerine getirebilirler. </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> (4) Kanun uyarınca oluşturulan internet sitesi, şirketlerin MERSİS numarası altında tescil edilir.</p>
        <p className='text-[12px] lg:text-[14px] font-semibold'>İnternet sitesinde yayımlanan içerik</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>  <span className='font-semibold'>MADDE 6 – </span>(1) İnternet sitesinin açılması ile birlikte aşağıdaki içerikler internet sitesinde sürekli olarak yayımlanır.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> a) Şirketin MERSİS numarası, ticaret unvanı, merkezi, taahhüt edilen ve ödenen sermaye miktarı ile anonim şirketlerde yönetim kurulu başkan ve üyelerinin, limited şirketlerde müdürlerin, sermayesi paylara bölünmüş komandit şirketlerde yöneticilerin ad ve soyadları.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>b) Bir tüzel kişinin; anonim şirketlerde yönetim kuruluna üye olarak limited şirketlerde müdür olarak seçilmesi durumunda; tüzel kişiyle birlikte, tüzel kişi adına tüzel kişi tarafından  belirlenen gerçek  kişinin de tescil ve ilan olunduğuna ilişkin açıklama, seçilen tüzel kişinin MERSİS numarası, ticaret unvanı, merkezi ve tüzel kişi ile birlikte tescil edilen gerçek kişinin adı ve soyadı.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>c) Seçilen denetçinin adı ve soyadı/unvanı, yerleşim yeri/merkezi, varsa tescil edilmiş şubesi. </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(2) Birinci fıkra uyarınca yayımlanan içeriklerde değişiklik olması halinde bu içeriklerin yeni hali, değişikliğin meydana geldiği tarihte internet sitesinde yayımlanır. </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(3) Şirketçe internet sitesinde en az altı aylık süre için yayımlanması gereken hususlar aşağıda belirtilmiştir. </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>a) Kanunun 149 uncu maddesinin birinci fıkrasına göre, birleşme sözleşmesi, birleşme raporu, son üç yılın finansal tabloları ile yıllık faaliyet raporları, gereğinde ara bilançoları ortakların incelemesine sunulmak üzere genel kurul kararından önceki otuz gün içinde internet sitesine konur. </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> b) Bu fıkranın (a) bendinde sayılan belgelerde inceleme yapma hakkının belirtildiği, bu belgelerin nereye tevdi edildiklerine ve nerelerde incelemeye hazır tutulduklarına ilişkin ilan, belgelerin tevdi tarihinden itibaren en az üç iş günü öncesinde internet sitesine konur. </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>c) Birleşmeye katılan şirketlerin, alacaklılarına, alacaklarının teminat altına alınması için talepte bulunabileceklerine dair sicil gazetesinde yedişer gün arayla üç defa yapılan ilan,  birinci ilanın sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>ç) Bölünmeye katılan şirketlerden her biri tarafından, Kanunun 171 inci maddesi uyarınca bölünme sözleşmesi veya planı, bölünme raporu, son üç yılın finansal tabloları ile yıllık faaliyet raporları ve varsa ara bilançoları üzerinde inceleme yapma hakkına işaret eden ve bu belgelerin nereye tevdi edildiklerine ve nerelerde incelemeye hazır tutulduklarına dair ilan, bölünme kararının alındığı tarihten iki ay önce internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>d) Bölünmeye katılan şirketler tarafından alacaklıların alacaklarını bildirmeye ve teminat verilmesi için talepte bulunmaya çağrılmasına ilişkin sicil gazetesinde yedişer gün arayla üç defa yapılan ilan, birinci ilanın sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>e) Şirkete fesih davası açılmış ise davanın açıldığı hususu, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>f) Şirkete açılan fesih davasına ilişkin kesinleşmiş olan mahkeme kararı, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>g) Genel kurulun toplantıya çağrılmasına ilişkin ilan en geç sicil gazetesinde yayımlandığı tarihte internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>ğ) Anonim şirket genel kurulunda, finansal tabloların ve buna bağlı konuların müzakeresinin bir ay sonraya ertelenmesi halinde, bu duruma ilişkin pay sahiplerine yapılan ilan, erteleme kararı tarihinden itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>h) Şirketin genel kurul toplantı tutanağı ile imtiyazlı pay sahipleri özel kurulunun toplantı tutanağı genel kurul tarihinden itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>ı) Kanunun 428 inci maddesi uyarınca organın temsilcisi, bağımsız temsilcisi ve kurumsal temsilciliğe ilişkin ilanlar, ilanın yayımlandığı gün internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>i) Genel kurul kararına karşı iptal veya butlan davasının açıldığı hususu ve duruşma günü, şirket sözleşmesine uygun olarak yapılan ilan tarihinden itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>j) Genel kurul kararının iptaline veya butlanına ilişkin kesinleşmiş mahkeme kararı, tescil tarihinden itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>k) Şirket sözleşmesinin değiştirilmesine ilişkin genel kurul kararı, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>l) Kayıtlı sermaye sisteminde yönetim kurulunun sermayenin artırılmasına ilişkin kararı, çıkarılmış sermayeyi gösteren esas sözleşme maddesinin yeni şekli, yeni payların itibarî değerleri, cinsleri, sayıları, imtiyazlı olup olmadıkları, imtiyazlı paylara ve rüçhan haklarına ilişkin sınırlamalar ve kullanılma şartları ile bunların süresi, prime dair kayıtlar ve bunun uygulanması hakkındaki kurallar şirket sözleşmesine uygun olarak yapılan ilan tarihinden itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>m) Yeni pay alma hakkının kullanılabilmesinin esaslarının belirlenmesine ilişkin yönetim kurulunun kararı, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>n) Esas sermayenin azaltılması durumunda, sermaye azaltılmasına gidilmesinin sebepleri ile azaltmanın amacı ve azaltmanın ne şekilde yapılacağına ilişkin ayrıntılı açıklamalar, bu açıklamaların da yer aldığı genel kurul toplantısına ilişkin çağrı ilanının sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>o) Genel kurulun esas sermayenin azaltılmasına ilişkin kararı üzerine alacaklılara sicil gazetesinde yedişer gün arayla üç defa yapılan ilan, birinci ilanın yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>ö) Mütemerrit pay sahibine temerrüde konu olan pay tutarını bir ay içinde ödemesi, aksi halde, ilgili paylara ilişkin haklarından yoksun bırakılacağı ve sözleşme cezasının isteneceğine ilişkin yapılan davet ve ihtar mesajı, bu davet ve ihtarın sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur. Nama yazılı pay senedi sahiplerine, davet ve ihtarın ilan yerine iadeli taahhütlü mektupla yapılması halinde, bu davet ve ihtar iadeli taahhütlü mektubun gönderildiği tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>p) Yönetim kurulunun hamiline yazılı pay senetlerinin bastırılmasına ilişkin kararı, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>r) Alacaklı oldukları, şirket defterlerinden veya diğer belgelerden anlaşılamayan ya da yerleşim yerleri bilinmeyen diğer alacaklılara yönelik şirketin sona ermiş bulunduğu konusunda bilgilendirilmelerine ve alacaklarını tasfiye memurlarına bildirmeye çağrılmalarına ilişkin sicil gazetesinde birer hafta arayla üç defa yapılan ilan, birinci ilanın yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>s) Şirketler topluluğuna dahil bir teşebbüs tarafından payların, Kanunun 198 inci maddesinde belirtilen oranlarda kazanılması veya elden çıkarılmasına ilişkin açıklama, gerçekleşme tarihinden itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>ş) Kanunun 966 ncı maddesinin birinci fıkrası uyarınca malik ve diğer hak sahiplerinin kimler olduğunun veya yerleşim yerlerinin belli olmadığı hallerde, geminin gemi sicilinden silinmesine ve belirlenen süreye ilişkin olarak sicil gazetesinde yapılan ilan, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesinde de ilan edilir.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>t) Şirketler topluluğuna dahil olan teşebbüsün ve sermaye şirketinin yönetim kurulu üyeleriyle yöneticilerinin, kendileri, eşleri, velayetleri altındaki çocukları ve bunların, sermayelerinin en az yüzde yirmisine sahip bulundukları ticaret şirketlerinin o sermaye şirketindeki payları ile ilgili olarak yapacakları açıklama, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>u) Şirketler arasında yapılan hakimiyet sözleşmesi sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>ü) Şirketteki pay sahibi/ortak sayısının bire düşmesi ya da şirketin tek pay sahipli/ortaklı olarak kurulması halinde, şirketin tek pay sahipli/ortaklı olduğu hususu ve tek pay sahibi/ortağın adı, soyadı, yerleşim yeri ve vatandaşlığına dair bilgiler sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>v) Şirket sözleşmesi ve değişiklikler kuruluşun ya da değişikliğin sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>y) Şirketin tescilinden itibaren iki yıl içinde bir işletme veya aynın, sermayenin onda birini aşan bir bedel karşılığında devralınmasına veya kiralanmasına ilişkin sözleşme sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>z) Yönetim kurulunun veya müdürler kurulunun temsile yetkili kişileri ve bunların temsil şekillerini gösterir kararı, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>aa) Anonim şirketlerde genel kurulun çalışma usul ve esaslarını içeren iç yönerge ilan tarihini izleyen beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>bb) Yönetim kurulunun rüçhan hakkının sınırlandırılmasının veya kaldırılmasının gerekçelerini, yeni payların primli ve primsiz çıkarılmasının sebeplerini, primin nasıl hesaplandığını gösteren raporu sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>cc) Sermayenin azaltılmasının sebepleri ile azaltmanın amacı ve azaltmanın ne şekilde yapılacağını gösterir yönetim/müdürler kurulunca hazırlanmış ve genel kurul tarafından onaylanmış sermayenin azaltılmasına ilişkin rapor, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>çç) Yönetim/müdürler kurulunun pay bedellerinin ödenmesine ilişkin çağrı ilanı yapıldığı tarihten itibaren en geç beş gün içinde internet sitesine konur.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>dd) Yönetim kurulunun mütemerrit pay sahibinin senedini iptal etmesine ilişkin kararı sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.    </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>ee) Yönetim kurulu veya müdürler kurulu ile genel kurul toplantılarının elektronik ortamda yapılması veya bu toplantılara elektronik ortamda katılım sağlanması hallerinde, elektronik ortam araçlarının etkin katılmaya elverişliliğinin ispatlandığı teknik rapor, sicil gazetesinde yayımlandığı tarihten itibaren en geç beş gün içinde internet sitesine konur.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(4) İnternet sitesinin bilgi toplumu hizmetlerine özgülenmiş kısmında yayımlanan içeriğin başına tarih ve parantez içinde “yönlendirilmiş mesaj” ibaresi konulur. Yönlendirilmiş mesaj zaman damgası ile oluşturulur ve aynı yöntemle değiştirilir.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(5) Kanun ve diğer kanunlar uyarınca yapılması gereken ilanlar, ilgili mevzuatta öngörüldüğü şekilde internet sitesinde yayımlanır.</p>
        <p className='text-[12px] lg:text-[14px] font-semibold'>Merkezi Veri Tabanı Hizmet Sağlayıcısı</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>MADDE 7 – </span>(1) MTHS’lerin faaliyetleri bu konuda Bakanlıkça verilmiş faaliyet iznine bağlıdır.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(2) Payları, Sermaye Piyasası Kanunu uyarınca MKK tarafından kayden izlenen şirketler için MTHS faaliyeti MKK tarafından yerine getirilir.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(3) MTHS sıfatıyla şirketler adına erişime açık bulundurulan bilgi ve belgeler 12 nci maddeye uygun olarak elektronik ortamda arşivlenir.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost font-semibold'>MTHS’nin yükümlülükleri        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>MADDE 8 </span>– (1) MTHS;</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>a) 11 inci maddede öngörülen teknik hususlar ve güvenlik kriterlerine uymakla,        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>b) Güvenli elektronik imzayı destekleyecek alt yapıyı sağlamakla,        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>c) Şirketlerin taleplerine göre internet sitesini barındırma veya veri tabanını muhafaza etme fonksiyonlarını yerine getirmekle,        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>ç) Yürütmekte olduğu faaliyete engel bir durum çıkması halinde bunu yedi gün içinde Bakanlığa bildirmekle,        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>d) Bakanlıkça talep edilmesi halinde, MERSİS ve diğer ilgili veri tabanları ile entegrasyonunu gerçekleştirmekle, <br/> yükümlüdür.</p>
        <p className='text-[12px] lg:text-[14px] font-semibold'>Rapor</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>MADDE 9 –</span> (1) MTHS, Bakanlığa her yıl Mart ayı sonuna kadar bir önceki yıla ilişkin verdiği hizmetlere ve hizmet verdiği şirketlerin bilgilerine dair bir rapor verir.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(2) Bakanlık tarafından münhasıran MTHS faaliyetine ilişkin istenecek diğer bilgi ve belgelerin de verilmesi gerekir.        </p>
        <p className='text-[12px] lg:text-[14px] font-semibold'>Şirketlerin yükümlülükleri</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>MADDE 10 –</span> (1) Şirketler, Kanunun 1524 üncü maddesi ve bu Yönetmelik hükümleri uyarınca internet sitesinin özgülenmiş kısmında bulunması öngörülen içeriği Bakanlık tarafından bir format belirlenmiş ise o formatta, belirlenmemişse elektronik ortamda MTHS’ye bildirir.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(2) Şirketler tarafından internet sitesinin bilgi toplumu hizmetlerine ayrılmış bölümünün şirkete ait internet sitesi üzerinden veya MTHS’ler üzerinden arama motorları tarafından kolay bulunabilmesi için, ana sayfada "bilgi toplumu hizmetleri şirket unvanı" şeklinde bir ibareye yer verilir.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(3) Sahip oldukları internet sitesi üzerinde bu bilgileri sağlayan şirketler, internet sitesinde yer alan içeriğin sitede yayımlanması, değiştirilmesi ve yenilenmesi gibi işlemlerde güvenli elektronik imza ve zaman damgası kullanırlar.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(4) Sahip oldukları internet sitesi üzerinde bu bilgileri sağlayan şirketler, ilgili bilgilere erişim için internet sitesi içinde “http://firmaalanadi/bilgitoplumuhizmetleri” adresinden yönlenmeyi sağlarlar. Şirketin farklı markalar ve pazarlama amaçları ile birden fazla alan adı sahibi olması durumunda her bir alan adı için bu ilke uygulanır.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(5) Şirketler, sahip oldukları internet sitelerinde erişime açık bulundurdukları bilgi ve belgeleri 12 nci maddeye uygun olarak elektronik ortamda arşivlerler.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(6) Şirketlerin sahip oldukları internet siteleri, 11 inci maddede öngörülen teknik hususlar ve güvenlik kriterlerine uygun olarak işletilir.</p>
        <p className='text-[12px] lg:text-[14px] font-semibold'>Teknik hususlar ve güvenlik kriterleri        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>MADDE 11 –</span> (1) Şirketlerin ve MTHS’lerin, bu Yönetmelik uyarınca yürütmekle yükümlü oldukları faaliyetler nedeniyle asgari yedekleme ve felaketten kurtarma planlarına, yetkisiz erişimlere ve saldırılara karşı gerekli ağ ve sistem güvenliğine sahip olmaları gerekir.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(2) Şirketler ve MTHS’ler, Kanunun ve bu Yönetmeliğin internet sitesinde bulunmasını öngördüğü asgari içeriğin üçüncü kişilere karşı erişilebilirliğini, bütünlüğünü, güvenliğini, değiştirilmezliğini ve inkar edilmezliğini sağlarlar.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(3) Şirketler ve MTHS’ler, verdikleri hizmetlere ilişkin sunucuları barındıran veri merkezlerini ve sistemlerini Türkiye Cumhuriyeti sınırları içinde kurup işletebilecekleri gibi bulut bilişim teknolojisi de dahil olmak üzere güncel teknolojileri kullanarak yurt dışında da kurup işletebilirler veya hizmet satın alabilirler.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(4) Şirketler ve MTHS’ler, işleyiş ve güvenlik kriterlerine ilişkin olarak;        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>a) ISO/IEC 27001 standardına uyarlar.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>b) Engelli bireylerin erişilebilirliği sağlamak için ise ISO/IEC 40500:2012 (W3C Web Content Accessibility Guidelines (WCAG) 2.0) standardına uyduklarını taahhüt ederler.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(5) Elektronik imzalı belgelerin uzun ömürlü olabilmesi için güvenli elektronik imzaların, Bilgi Teknolojileri ve İletişim Kurumu tarafından 2/7/2012 tarihli ve 2012/DK-15/299 sayılı Kurul Kararı ile yayımlanan Elektronik İmza Kullanım Profilleri Rehberinde yer alan Arşiv Elektronik İmza Uzun Dönemli ve SİL Kontrollü Güvenli Elektronik İmza Politikaları (Profil P3)’na veya Uzun Dönemli ve ÇİSDuP Kontrollü Güvenli Elektronik İmza Politikaları (Profil P4)’na uygun olarak üretilmesi ve bu imzaların saklanması gereken süre içinde belirli zaman aralıklarında arşiv formatında güncellenmesi gereklidir.        </p>

        <p className='text-[12px] lg:text-[14px] font-semibold'>Elektronik arşivleme        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>MADDE 12 –</span> (1) İnternet sitesinde yayımlanan içerik, ilgili mevzuatta daha uzun bir süre öngörülmedikçe internet sitesindeki yayımının son bulduğu tarihten itibaren beş yıl süre ile elektronik olarak arşivlenir.        </p>

        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(2) İçeriğin MERSİS ve/veya diğer veri tabanlarına bir MTHS aracılığıyla aktarılması Bakanlık tarafından zorunlu kılınmışsa bu içerik Bakanlık tarafından belirlenen format ve standartlara uygun olarak ilgili veri tabanına aktarılabilir.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(3) İnternet sitesinde yer alacak içeriğin arşivlenmesinde güvenli elektronik imza ve zaman damgası kullanılır.        </p>
        <p className='text-[12px] lg:text-[14px] font-semibold'>Ücretlerin tespiti </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>MADDE 13 –</span> (1) Bakanlık gerekli gördüğü hallerde, MTHS’ler tarafından şirketlere verilen hizmetler karşılığında talep edilecek ücretleri veya bunların üst sınırlarını belirlemeye yetkilidir.   </p>
        <p className='text-[12px] lg:text-[14px] font-semibold'>Teknik rapor</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>MADDE 14 –</span> (1) Şirketler ve MTHS’ler internet sitelerinin özgülenmiş kısımlarının bu Yönetmelik ve Kanunun 1524 üncü madde hükümlerine uygunluğunu, ikinci fıkrada belirtilen kurumlara tespit ettirmek ve söz konusu kurumlar tarafından düzenlenen teknik raporu Bakanlığa vermekle yükümlüdür. MTHS hizmeti verecek sermaye şirketleri ayrıca kendi bilgilerini özgüledikleri internet sitelerinin uygunluğunu da bu raporda tespit ettirir. </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(2) Teknik rapor, Türkiye Bilimsel ve Teknolojik Araştırma Kurumu veya bu alanda denetim yapmaya yetkilendirilmiş bağımsız denetim şirketlerinden alınabilir. Bu rapor, iki yılda bir yenilenir ve birinci fıkrada öngörülen işlemler tekrarlanır.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(3) Teknik raporda, şirketlerin ve MTHS’lerin 8, 10 ve 11 inci maddelerde belirtilen hususlara uygunluğu tespit edilir.</p>
        <p className='text-[12px] lg:text-[14px] font-semibold'>Bakanlık izni</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>MADDE 15 –</span> (1) Özel hukuk tüzel kişileri, MTHS olma talebini içeren dilekçeyi 14 üncü madde uyarınca aldığı teknik raporla birlikte Bakanlığa ibraz etmek suretiyle izin talebinde bulunurlar. Ancak MTHS hizmeti vermek için izin başvurusunda bulunan sermaye şirketlerinin,  Kanun ve bu Yönetmelik hükümlerine uygun olarak kendi bilgilerini özgüleyecekleri internet sitesine sahip olmaları gerekir.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(2) Bakanlık, izin taleplerini bir ay içinde sonuçlandırır. İzin şartlarını eksiksiz olarak yerine getiren MTHS’ye Bakanlıkça faaliyet izni verilir.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(3) Bakanlık, inceleme sonucunda izin şartlarından bir veya birkaçının eksikliğini veya yerine getirilmediğini tespit ederse bu eksikliklerin giderilmesi için talep sahibine, bir ayı geçmemek üzere süre verebilir. Eksikliklerin bu süre içinde giderilmesi halinde ikinci fıkra uyarınca faaliyet izni verilir.        </p>
        <p className='text-[12px] lg:text-[14px] font-semibold'>MTHS’lerin faaliyetlerinin sona ermesi        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>MADDE 16 –</span> (1) MTHS’lerin faaliyetinin devamı sırasında; 11 inci maddede yer alan faaliyet şartlarından birinin veya birkaçının kaybedildiğinin yenilenen teknik raporda tespit edilmesi halinde, Bakanlık tarafından MTHS’ye bu eksikliğin giderilmesi için üç aya kadar süre verilir. Gerekli hallerde MTHS’ye bir ayı aşmamak üzere ek süre verilebilir. Verilen süreler içinde MTHS’nin faaliyeti sadece sözleşme yaptığı şirketlere hizmet vermekle sınırlı olmak üzere devam eder. Ancak MTHS, hizmet verdiği şirketlere teknik raporla tespit edilen eksiklikleri kayıtlı elektronik posta yoluyla derhal bildirmekle yükümlüdür. Verilen süreler içinde eksikliğin giderilmemesi halinde MTHS’nin faaliyetine Bakanlık tarafından son verilir. </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(2) MTHS, kendi isteğiyle faaliyetine son vereceği tarihten en az üç ay önce durumu; Bakanlığa yazılı olarak bildirir, faaliyetine son verme kararını internet sitesinde yayımlar ve hizmet verdiği şirketlere bu durumu kayıtlı elektronik posta ile bildirir.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(3) Birinci fıkraya göre MTHS’nin teknik raporla tespit edilen eksikliklerini veya ikinci fıkraya göre kendi isteğiyle faaliyetine son vereceğini kayıtlı elektronik posta yoluyla öğrenen hizmet alan şirketler, kendi belirleyecekleri diğer bir MTHS’den hizmet alabilirler.        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(4) MTHS, Bakanlığın faaliyete son verme kararının tebliğinden veya faaliyetine son verme kararını Bakanlığa bildirdiği tarihten itibaren hizmet sağlayamaz.</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'>(5) Faaliyetine son veren veya verilen MTHS’ler, oluşturdukları arşivi derhal hizmet verdiği şirketlere devreder.</p>
        <h4 className='text-[20px] lg:text-[24px] font-jost font-medium mb-[15px]'>ÜÇÜNCÜ BÖLÜM</h4>
        <h5 className='text-[14px] lg:text-[16px] font-semibold'>Son Hükümler        </h5>
        <p className='text-[12px] lg:text-[14px] font-semibold'>İnternet sitesi yükümlülüğünün yürürlüğe girdiği tarihten önce kurulan şirketler</p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>GEÇİCİ MADDE 1 –</span> (1) Bu Yönetmeliğin yürürlüğe girdiği tarihten önce kurulmuş şirketlerin, 1/7/2013 tarihinden itibaren üç ay içinde internet sitesi açmaları ve bu sitenin belirli bir bölümünü şirketçe kanunen yapılması gereken ilanların yayımlanması için özgülemeleri gerekir. İnternet sitesi var olan şirketlerin ise, aynı süre içerisinde sitelerinin belirli bir bölümünü şirketçe kanunen yapılması gereken ilanların yayımlanmasına özgülemeleri gerekir. </p>
        <p className='text-[12px] lg:text-[14px] font-semibold'>Yürürlük </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>MADDE 17 –</span> (1) Bu Yönetmelik 1/7/2013 tarihinde yürürlüğe girer.</p>
        <p className='text-[12px] lg:text-[14px] font-semibold'>Yürütme        </p>
        <p className='text-[12px] lg:text-[14px] leading-normal font-jost'> <span className='font-semibold'>MADDE 18 –</span> (1) Bu Yönetmelik hükümlerini Gümrük ve Ticaret Bakanı yürütür.</p>
    </div>
    </div>
  )
}

export default WebRuleSection
